"""Frozen G2/G3 tables for assert_gate_tauri_split."""
from __future__ import annotations

# main() assert_* calls on master today (including assert_app_notarize).
_SPLIT_MAIN_ASSERTS = (
    "assert_app_notarize",
    "assert_chat_bubbles",
    "assert_day_separators",
    "assert_local_tz_display",
    "assert_jump_day_heading",
    "assert_jump_day_heading_review",
    "assert_jump_day_heading_freeze",
    "assert_jump_day_heading_stutter",
    "assert_jump_day_heading_stutter2",
    "assert_jump_day_heading_image",
    "assert_jump_day_heading_fold",
    "assert_timeline_latest",
    "assert_conversation_switcher",
    "assert_timeline_platform_chips",
    "assert_timeline_kind_filter",
    "assert_gmail_timeline_rows",
    "assert_people_sidebar_no_x_scroll",
    "assert_people_filter_identity",
    "assert_people_list_lock",
    "assert_boot_spinner",
    "assert_photo_lightbox",
    "assert_voice_note_player",
    "assert_voice_note_seek",
    "assert_cas_video_pdf",
    "assert_bubble_linkify",
    "assert_bubble_search",
    "assert_reveal_archive",
    "assert_first_run",
    "assert_font_density",
    "assert_reopen_last_session",
    "assert_remember_include_groups",
    "assert_remember_include_groups_fold",
    "assert_persist_window_frame",
    "assert_light_chrome",
    "assert_chrome_locale_panes",
    "assert_virtualized_timeline",
    "assert_variable_height_timeline",
    "assert_search_platform_select",
    "assert_search_conversation_kind",
    "assert_search_person_picker",
    "assert_search_jump_to_message",
    "assert_search_attachment_filter",
    "assert_search_safe_highlight",
    "assert_search_filters_secondary",
    "assert_search_hit_density",
    "assert_review_identifiers",
    "assert_window_title",
    "assert_macos_menu",
    "assert_chrome_locale",
    "assert_keyboard_map",
    "assert_find_in_conversation",
    "assert_find_in_conversation_count",
    "assert_find_in_conversation_review",
    "assert_chrome_search_field",
    "assert_search_as_you_type",
    "assert_custom_titlebar",
    "assert_people_sidebar_collapse",
    "assert_person_inspector",
    "assert_keyboard_list_arrows",
    "assert_command_palette",
    "assert_command_palette_people_cap",
    "assert_command_palette_field_keys",
    "assert_command_palette_clipboard",
    "assert_focus_aria_audit",
    "assert_contrast_tokens",
    "assert_appearance_os",
    "assert_status_tokens",
    "assert_import_progress",
    "assert_import_cancel",
    "assert_review_chrome",
    "assert_sidebar_undo_chrome",
    "assert_motion",
    "assert_a11y_listbox_focus_motion",
    "assert_human_time_people",
    "assert_drag_drop_import",
    "assert_copy_reveal_cas",
    "assert_defer_doctor_cas",
    "assert_design_tokens",
    "assert_typography",
    "assert_lucide_icons",
    "assert_owned_primitives",
    "assert_empty_next_action",
    "assert_loading_skeletons",
    "assert_timeline_append_skeleton_guard",
    "assert_inflight_audible_status",
    "assert_recoverable_toasts",
    "assert_partial_pane_errors",
    "assert_partial_retry_generation",
    "assert_timeline_grouped_runs",
    "assert_timeline_bubble_hierarchy",
    "assert_timeline_attach_slot",
    "assert_product_split",
    "assert_recent_archives",
    "assert_recent_archives_fold",
    "assert_switch_archive",
    "assert_switch_archive_fold",
    "assert_switch_archive_err",
)

# #219 keep-check that #278 folded (pane or en pack).
_SPLIT_219_FOLD_TOKENS = (
    "Loading review queue",
    "identifierLabel",
    "reviewList",
    "reviewAccept",
    "reviewReject",
)

_SPLIT_PROTECTED_PREFIXES: dict[str, tuple[str, ...]] = {
    "assert_review_identifiers": (
        "#128: ReviewPane.svelte required (review card identifier chrome lives there)",
        "#128: web/lib/api.ts required (ReviewPanel type surface)",
        "#128: api.ts must declare export type ReviewPanel = { … }",
        "#128: unclosed ReviewPanel type in api.ts",
        "#128: ReviewPanel must include identifiers[] (kind + value_normalized per entry — not only display_name / platforms)",
        "#128: ReviewPane must render panel.identifiers (kind + value_normalized under the title — not only display_name / platforms)",
        "#128: ReviewPane must show identifier kind and value_normalized as text (bindings on the panel loop, or a small formatter used there) — not only panelTitle(display_name + platforms)",
        "#128: do not use raw person_id as the primary identifier label",
        "#128: ReviewPane samples must stay text nodes — no {@html on sample body}",
        "#128: ReviewPane must still render sample body_text as text",
        "#128: sample bodies must remain text bindings of body_text (not HTML inject)",
        "#128: keep the evidence list on the review card",
        "#128: keep the score on the review card",
        "#128: keep Accept on the review card",
        "#128: keep Reject on the review card",
        "#128: keep display_name / panel title chrome; identifiers sit under it",
        "#128: keep platforms on the panel surface (identifiers are additive)",
        "#128: do not invent name_score raise/lower UI (threshold policy is #103; this issue only surfaces identifiers)",
        "#128: ReviewPanel.identifiers entries must expose kind + value_normalized (inline or named type; platform optional)",
    ),
    "assert_status_tokens": (
        "#219: crates/interlace-tauri/web/**/*.svelte required (status tokens)",
        "#219: web/app.css required (warning / success status tokens)",
        "#219: App.svelte required (cloud banner + Doctor found box)",
        "#219: DoctorPane.svelte required (issues card uses warning token)",
        "#219: data-cloud-warning required (warning token, not muted-only)",
        "#219: data-cloud-warning must not use amber-* / yellow-* / emerald-* / green-* (warning token only)",
        "#219: data-cloud-warning must use a warning token class / var(--warning) / var(--color-warning) (not muted-only, not amber-*)",
        "#219: App.svelte “Doctor found” box required (warning token, not text-destructive)",
        "#219: App.svelte “Doctor found” box must use a warning token (not text-destructive as the status color)",
        "#219: DoctorPane.svelte issues card required (warning token, not text-destructive)",
        "#219: DoctorPane.svelte issues card must use a warning token (not text-destructive as the status color)",
        "#219: data-import-done required (muted token classes or success tokens; no bg-gradient / confetti / celebration)",
        "#219: data-import-done must use muted token classes or success tokens (no bg-gradient / confetti / celebration)",
        "#219: data-import-done must not use bg-gradient / confetti / celebration",
        "#219: no amber-* / yellow-* / emerald-* / green-* on cloud / doctor / import-done surfaces. Found:\n  ",
        "#219: no confetti / Audio( / celebration copy. Found:\n  ",
        "#219: docs/user/app.md required — warning token + quiet import done",
        "#219: docs/user/app.md must say cloud / doctor warnings use the warning token",
        "#219: docs/user/app.md must say import done is quiet (muted or success)",
        "#219: not in scope — no review-queue chrome rewrite (#221)",
        '#219: keep id="q" as the canonical query field (#208)',
        "#219: keep data-people-sidebar (#159 / #212)",
        "#219: keep the overlay titlebar (#211)",
        "#219: keep data-person-inspector (#213)",
        "#219: do not soften tauri CSP",
        "#219: keep #217 light --color-muted-foreground HSL L ≤ 40 (@theme / non-dark :root)",
        "#219: keep #217 dark --color-muted-foreground HSL L ≥ 62 (inside prefers-color-scheme: dark)",
        "#219: keep #217 --search-mark / --color-search-mark on both sides",
        "#219: keep #217 .search-mark on var(--search-mark)",
        "#219: keep #218 --overlay / --scrim / --lightbox-scrim",
        "#219: keep #218 — no Theme / Appearance menu / data-theme",
    ),
    "assert_import_progress": (
        "#220: data-import-cancel required in ImportPane.svelte (Cancel while running)",
        "#220: no thread:: kill / JoinHandle:: abort as cancel (do not kill the import thread)",
        "#220: Status running must still be rendered in the import pane",
        "#220: keep data-import-done (quiet counts; no Dialog / bg-gradient / confetti)",
        "#220: data-import-done must not be wrapped in a Dialog",
        "#220: data-import-done must not use bg-gradient / confetti / celebration",
        "#220: do not console.log the import path",
        "#220: do not toast the import path",
        "#220: no parallel-import UI",
        "#220: no fetch( / HTTP import",
        "#220: no background GC button on Import",
        "#220: docs/user/app.md required — progress visible + quiet done",
        "#220: docs/user/app.md must say import progress is visible",
        "#220: docs/user/app.md must say import done stays quiet",
        '#220: keep id="q" as the canonical query field (#208)',
        "#220: keep data-people-sidebar (#159 / #212)",
        "#220: keep the overlay titlebar (#211)",
        "#220: keep data-person-inspector (#213)",
        "#220: do not soften tauri CSP",
        "#220: keep #219 --warning / --color-warning in light and dark",
        "#220: keep #219 data-import-done",
        "#220: keep #218 --overlay / --scrim / --lightbox-scrim",
        "#220: keep #218 — no Theme / Appearance menu / data-theme",
    ),
    "assert_review_chrome": (
        "#221: ReviewPane.svelte required (review queue chrome lives there)",
        "#221: ReviewPane.svelte must import Card from $lib/components/ui/card and Separator from $lib/components/ui/separator",
        "#221: data-review-card required on the open review card",
        "#221: keep Accept on the review card (explicit >Accept<)",
        "#221: keep Reject on the review card (explicit >Reject<)",
        "#221: queue/detail markup must not show #{r.id} / person ${ / person ${r.right_person_id / Accept review ${id} (found ",
        "#221: keep identifierLabel or value_normalized on the review card",
        "#221: ReviewPane samples must stay text nodes — no {@html",
        "#221: sample bodies must remain text bindings of body_text",
        "#221: ReviewPane must call linkEvents (undo lives on the pane)",
        "#221: ReviewPane must call undo (api.undo after Accept)",
        "#221: data-review-undo required on the Review pane Undo control",
        "#221: do not undo events[0] blindly — skip split_person / already-undone / system import links",
        "#221: Review undo must skip split_person and already-undone events (undo_of)",
        "#221: ConfirmDialog.svelte required (go() must close before await onconfirm())",
        "#221: ConfirmDialog.svelte go() required (set open = false before await onconfirm())",
        "#221: ReviewPane must not await onChanged() after undo (People refresh must not block the confirm callback)",
        "#221: ConfirmDialog must refuse open = true while busy (or leave Cancel enabled so a resurrected overlay is dismissable)",
        "#221: ConfirmDialog go() must catch onconfirm and have an onerror / onError prop",
        "#221: App.svelte ConfirmDialog required",
        "#221: App.svelte ConfirmDialog must pass onerror / onError / showErr",
        "#221: Review Undo disabled must mention resolving (not only undoing)",
        "#221: ReviewPane requestUndo() required",
        "#221: requestUndo() must return early when resolving",
        "#221: do not invent name_score raise/lower UI (threshold policy is not this issue)",
        "#221: sample loop must stay {#each panel.samples (do not add a second body dump)",
        "#221: do not add a second body dump — keep the existing panel.samples loop",
        "#221: docs/user/app.md required — Review + undo / reversible / no raw person id (or identifiers + undo)",
        "#221: docs/user/app.md must say Review + undo / reversible / no raw person id (or identifiers + undo)",
        '#221: keep id="q" as the canonical query field (#208)',
        "#221: keep data-people-sidebar (#159 / #212)",
        "#221: keep the overlay titlebar (#211)",
        "#221: keep data-person-inspector (#213)",
        "#221: do not soften tauri CSP",
        "#221: keep #219 --warning / --color-warning in light and dark",
        "#221: keep #220 data-import-cancel",
        "#221: keep #218 --overlay / --scrim / --lightbox-scrim",
        "#221: keep #218 — no Theme / Appearance menu / data-theme",
        "#221: ConfirmDialog go() must set open = false before await onconfirm() (or not await onconfirm)",
        "#221: Accept/Reject callbacks must try/catch and call onError (same as runUndo)",
    ),
    "assert_motion": (
        "#222: crates/interlace-tauri/web/**/*.svelte required (motion)",
        "#222: palette must import fade / fly / slide from svelte/transition (App.svelte and/or CommandPalette.svelte)",
        "#222: inspector must import fade / fly / slide from svelte/transition",
        "#222: data-command-palette (or commandOpen root) required for fade / fly / slide",
        "#222: data-command-palette (or commandOpen root) must use transition:fade / fly / slide with duration 150–250 (or 0 when reduced)",
        "#222: data-person-inspector required for fade / fly / slide",
        "#222: data-person-inspector must use transition:fade / fly / slide with duration 150–250 (or 0 when reduced)",
        "#222: toast.svelte required (keep transition:fade 150–250)",
        "#222: toast must still use transition:fade",
        "#222: toast transition:fade duration must be 150–250 (or 0 if reduced)",
        "#222: no spring / bounce / elastic / lottie / celebration / confetti in product Svelte. Found:\n  ",
        "#222: reduced-motion path must use matchMedia / MediaQuery / prefersReducedMotion in JS (CSS transition-duration: 0.01ms is not enough for Svelte transitions)",
        "#222: palette / inspector / toast Svelte transitions must use duration 0 (or skip) when reduced motion",
        "#222: keep #133 @media (prefers-reduced-motion: reduce) in CSS (or Tailwind motion-reduce)",
        "#222: keep #133 reduced-motion animation: none (boot spinner must not spin)",
        "#222: keep #133 prefers-reduced-motion CSS (transition: none / transition-duration: 0)",
        "#222: keep boot spinner reduced-motion (#133 / #156 — disable boot-spin under reduce)",
        "#222: docs/user/app.md required — fade/slide + reduced motion instant + no celebration / no auto-play",
        "#222: docs/user/app.md must say palette / inspector / toast use a short fade / slide",
        "#222: docs/user/app.md must say reduced motion makes them instant",
        "#222: docs/user/app.md must say no celebration",
        "#222: docs/user/app.md must say no auto-playing media",
        '#222: keep id="q" as the canonical query field (#208)',
        "#222: keep data-people-sidebar (#159 / #212)",
        "#222: keep the overlay titlebar (#211)",
        "#222: keep data-person-inspector (#213)",
        "#222: do not soften tauri CSP",
        "#222: keep #219 --warning / --color-warning in light and dark",
        "#222: keep #220 data-import-cancel",
        "#222: keep #221 data-review-card",
        "#222: keep #221 data-review-undo",
    ),
}

__all__ = [
    "_SPLIT_MAIN_ASSERTS",
    "_SPLIT_219_FOLD_TOKENS",
    "_SPLIT_PROTECTED_PREFIXES",
    "annotations",
]
